import type { Metadata } from "next";
import Image from "next/image";
import { MarketingPage } from "../components/MarketingPage";

export const metadata: Metadata = { title: "About WykSofts Inc.", description: "Meet WykSofts Inc. and founder Wycliff Njenga, a Nairobi software company serving teams worldwide." };

export default function AboutPage() {
  return (
    <MarketingPage eyebrow="About WykSofts" title="A product partner for ambitious, practical ideas." intro="We are a Nairobi-based software company helping organizations turn important ideas into thoughtful digital products that last.">
      <section className="about section"><p className="section-kicker">What guides us</p><div className="about-layout"><h2>Built with care.<br />Made to last.</h2><div className="about-copy"><p className="about-lead">More than code: clear product thinking, thoughtful design, dependable engineering, and a team that sees the bigger picture.</p><div className="principles"><article><span>01</span><h3>Business first</h3><p>Every technical decision starts with the outcome it needs to create for the business and its users.</p></article><article><span>02</span><h3>Quality throughout</h3><p>Thoughtful design, clean engineering, and clear communication are built into the process.</p></article><article><span>03</span><h3>Ready to grow</h3><p>We build foundations that can evolve as customers, operations, and ambition expand.</p></article></div><div className="company-facts"><div><span>Based in</span><strong>Mirage Towers, Nairobi</strong></div><div><span>Working model</span><strong>Local insight, global delivery</strong></div><div><span>Core disciplines</span><strong>Strategy, design &amp; engineering</strong></div></div></div></div></section>
      <section className="founder section"><div className="founder-portrait"><Image src="/projects/wycliff-njenga-brand.jpg" alt="Wycliff Njenga, Founder and CEO of WykSofts Inc." width={1254} height={1254} unoptimized /><span aria-hidden="true">Founder / CEO</span></div><div className="founder-copy"><p className="section-kicker">Meet the founder</p><h2>Wycliff Njenga</h2><p className="founder-role">Founder &amp; CEO · WykSofts Inc.</p><p className="founder-bio">With more than 10 years in technology, Wycliff combines product thinking, thoughtful design, and dependable engineering to move ideas from early concepts to useful, scalable solutions. His experience spans customer-facing mobile products, business websites, software integrations, and cloud-based systems. Through WykSofts, he focuses on clear communication, practical technology, and long-term client value.</p><div className="founder-facts"><div><strong>10+</strong><span>Years in technology</span></div><div><strong>Nairobi</strong><span>Building for clients worldwide</span></div></div><div className="founder-skills"><span>Product strategy</span><span>Mobile apps</span><span>Web platforms</span><span>Custom software</span><span>API integrations</span><span>Cloud &amp; AI</span></div><div className="founder-links"><a href="https://www.linkedin.com/in/wycliff-njenga-5973b512a/" target="_blank" rel="noreferrer">LinkedIn <span>↗</span></a><a href="https://github.com/wykeenjenga" target="_blank" rel="noreferrer">GitHub <span>↗</span></a></div></div></section>
      <section className="launch-film section"><div className="launch-film-heading"><p className="section-kicker light">WykSofts in motion</p><h2>Ideas become products. Products create momentum.</h2><p>A short introduction to the thinking, craft, and ambition behind WykSofts Inc.</p><a href="/media/wyksofts-launch.mp4" download>Download launch film <span>↓</span></a></div><div className="launch-film-stage"><span className="launch-film-index">00:18 / Launch film</span><video muted loop playsInline controls preload="metadata" poster="/media/wyksofts-launch-poster.jpg"><source src="/media/wyksofts-launch.mp4" type="video/mp4" />Your browser does not support embedded video.</video></div></section>
    </MarketingPage>
  );
}
