create table if not exists public.wyksofts_website_visits (
  id bigint generated by default as identity primary key,
  visited_at timestamptz not null default now(),
  session_id uuid not null,
  path text not null check (char_length(path) between 1 and 300),
  referrer_domain text check (referrer_domain is null or char_length(referrer_domain) <= 253),
  device_type text not null check (device_type in ('desktop', 'mobile', 'tablet')),
  utm_source text check (utm_source is null or char_length(utm_source) <= 120),
  utm_campaign text check (utm_campaign is null or char_length(utm_campaign) <= 160)
);

alter table public.wyksofts_website_visits enable row level security;

revoke all on table public.wyksofts_website_visits from anon, authenticated;
grant insert (session_id, path, referrer_domain, device_type, utm_source, utm_campaign)
  on public.wyksofts_website_visits to anon, authenticated;
grant select on public.wyksofts_website_visits to authenticated;
grant usage, select on sequence public.wyksofts_website_visits_id_seq to anon, authenticated;

drop policy if exists "Visitors can record anonymous page views" on public.wyksofts_website_visits;
create policy "Visitors can record anonymous page views"
on public.wyksofts_website_visits for insert to anon, authenticated
with check (
  path not like '/admin%'
  and path not like '%#%'
  and path not like '%?%'
);

drop policy if exists "WykSofts admin can read website analytics" on public.wyksofts_website_visits;
create policy "WykSofts admin can read website analytics"
on public.wyksofts_website_visits for select to authenticated
using (lower(((select auth.jwt()) ->> 'email')) = 'hello@wyksoftsinc.com');

create index if not exists wyksofts_website_visits_visited_at_idx
  on public.wyksofts_website_visits (visited_at desc);
create index if not exists wyksofts_website_visits_path_visited_at_idx
  on public.wyksofts_website_visits (path, visited_at desc);
create index if not exists wyksofts_website_visits_session_visited_at_idx
  on public.wyksofts_website_visits (session_id, visited_at desc);
